services:
  web-server:
    image: web-server:1.0.0
    build:
      context: ../..
      dockerfile: ./examples/docker/Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8080
    ports:
      - 8080:8080
