services:
  keycloak:
    image: quay.io/keycloak/keycloak
    entrypoint: ["/bin/bash", "-c"]
    command:
      - rm -rf /opt/keycloak/data/h2 /opt/keycloak/data/transaction-logs && /opt/keycloak/bin/kc.sh start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "9090:8080"
